### ISSUE TITLE
Robots should avoid railway track

### ISSUE THREAD

**Issue by andreboogaards** [kyranf/robotarmyfactorio#89] opened 2016-12-04 15:21 UTC
Crossing a track occasionally will be unavoidable, but ideally robots would take the shortest route across a track, not move along the track and not come to a halt on track (nor ideally one tile next to it)

**Comment by arrdem** [comment] 2016-12-04 19:07
Dupe of #32, which already has some commentary on how difficult it would be to implement this.

**Comment by kyranf** [comment] 2016-12-04 19:12
Factorio pathfinding is out of my control, other than requesting move to location X. The checking of rail tiles underneath each droid or even nearby a squad position is not worth the CPU usage. @arrdem  is correct, see discussions in Issue 32

**Closed by kyranf** 2016-12-04 19:12 UTC
