### ISSUE TITLE
[dev] while trying to place a terminator

### ISSUE THREAD

**Issue by szentigrad3** [kyranf/robotarmyfactorio#51] opened 2016-08-05 02:00 UTC
4349.508 Error MainLoop.cpp:665: Exception at tick 5114866: Error while running the event handler: __robotarmy__/robolib/robotarmyhelpers.lua:292: attempt to index local 'squad' (a nil value)
4349.508 Error MultiplayerManager.cpp:129: MultiplayerManager failed: "Error while running the event handler: __robotarmy__/robolib/robotarmyhelpers.lua:292: attempt to index local 'squad' (a nil value)"

**Comment by kyranf** [comment] 2016-08-05 02:01
Awesome, thanks. I'll check it out right now. I've probably actually fixed it already, and i'm uploading the new code very soon. I'll comment again when i've identified what this particular crash was caused by

**Comment by kyranf** [comment] 2016-08-05 02:10
Okay, this is literally a duplicate of #50

**Comment by kyranf** [comment] 2016-08-05 02:13
Please try the newly updated dev files @szentigrad3

**Comment by kyranf** [comment] 2016-08-11 03:23
closing until further info/new report

**Closed by kyranf** 2016-08-11 03:23 UTC
