### ISSUE TITLE
crash - with crashreport

### ISSUE THREAD

**Issue by Johannnnnn** [kyranf/robotarmyfactorio#37] opened 2016-07-19 17:46 UTC
so I crashed 
I think it is due to this mod - because looking through the forums I only found a post by you

`   0.001 2016-07-19 19:37:54; Factorio 0.13.6 (build 23136, win64, alpha)
   0.001 Operating system: Windows 10 
   0.001 Program arguments: "C:\Program Files\Factorio\bin\x64\factorio.exe" 
   0.001 Read data path: C:/Program Files/Factorio/data
   0.001 Write data path: C:/Users/JohanII/AppData/Roaming/Factorio
   0.001 Binaries path: C:/Program Files/Factorio/bin
   0.016 Graphics options: [FullScreen: false] [VSync: true] [UIScale: 100%] [MultiSampling: OFF] [Graphics quality: normal] [Video memory usage: all] [Light scale: 20%] [Screen: 255] [DXT: false]
   0.018 Available display adapters: 1
   0.019  [0]: \\.\DISPLAY1 - Intel(R) HD Graphics 4000 {0x05, [0,0], 1920x1080, 32bit, 60Hz}
   0.019 Create display on adapter 0. Size 1280x720 at position [310, 162].
   0.064 Initialised Direct3D:[0] NVIDIA GeForce GTX 680M     ; driver: nvd3dumx.dll 10.18.13.5362
   0.066     Video memory size (dedicated video/dedicated system/shared system/available): 4027/0/8137/4092 MB
   0.098 Desktop composition is active.
   0.193 Loading mod core 0.0.0 (data.lua)
   0.197 Loading mod base 0.13.6 (data.lua)
   0.302 Loading mod blueprint-string 3.0.3 (data.lua)
   0.370 Loading mod AutoTrash 0.1.5 (data.lua)
   0.437 Loading mod EvoGUI 0.4.105 (data.lua)
   0.502 Loading mod Expanded_Robot_Tech 0.4.1 (data.lua)
   0.579 Loading mod Landfill 2.1.10 (data.lua)
   0.644 Loading mod Larger Inventory 1.0.1 (data.lua)
   0.711 Loading mod MoreLight 1.1.1 (data.lua)
   0.790 Loading mod RailTanker 1.3.32 (data.lua)
   0.790 Script data.lua:18: done
   0.856 Loading mod robotarmy 0.2.0 (data.lua)
   0.931 Loading mod TheFatController 0.4.18 (data.lua)
   1.018 Loading mod YARM 0.7.102 (data.lua)
   1.087 Loading mod long-reach 0.0.5 (data-final-fixes.lua)
   1.156 Loading mod RailTanker 1.3.32 (data-final-fixes.lua)
   1.229 Checksum for core: 714099156
   1.229 Checksum for mod base: 1855085279
   1.229 Checksum for mod blueprint-string: 2370144521
   1.229 Checksum for mod autofill: 0
   1.229 Checksum for mod AutoTrash: 1587932681
   1.229 Checksum for mod clock: 0
   1.229 Checksum for mod EvoGUI: 1040096666
   1.229 Checksum for mod Expanded_Robot_Tech: 450750456
   1.229 Checksum for mod Landfill: 3661776105
   1.229 Checksum for mod Larger Inventory: 32563986
   1.229 Checksum for mod long-reach: 315959611
   1.229 Checksum for mod MoreLight: 3037131012
   1.229 Checksum for mod RailTanker: 886730006
   1.229 Checksum for mod robotarmy: 2391337320
   1.229 Checksum for mod TheFatController: 2087045025
   1.229 Checksum for mod YARM: 1471126532
   1.825 Initial atlas bitmap size is 16384
   1.829 Created atlas bitmap 16384x10348
   2.215 Created atlas bitmap 4096x996
   7.633 Sprites loaded
   7.633 Convert atlas 4096x996 to: trilinear-filtering 
   7.856 Loading sounds...
   9.527 Custom inputs active: 2
   9.527 Info Updater.cpp:750: Downloading https://www.factorio.com/updater/get-available-versions?username=J0h4n&token=<private>&apiVersion=2
  10.564 A newer version of Factorio exists, but it can no longer be obtained using automatic updates. Please download the latest version manually from http://www.factorio.com.
  10.600 Factorio initialised
  20.966 Loading map C:/Users\JohanII\AppData\Roaming\Factorio\saves\_autosave3.zip
  20.992 Info Scenario.cpp:127: Map version 0.13.6-0
  21.618 Checksum for script C:/Users/JohanII/AppData/Roaming/Factorio/temp/currently-playing/control.lua: 900459546
  21.626 Checksum for script __blueprint-string__/control.lua: 1853645101
  21.630 Checksum for script __autofill__/control.lua: 2546383396
  21.633 Checksum for script __AutoTrash__/control.lua: 3595631901
  21.634 Checksum for script __clock__/control.lua: 2990318672
  21.637 Checksum for script __EvoGUI__/control.lua: 1485927187
  21.638 Checksum for script __Landfill__/control.lua: 530583378
  21.640 Checksum for script __RailTanker__/control.lua: 843196296
  21.643 Checksum for script __robotarmy__/control.lua: 4219419030
  21.649 Checksum for script __TheFatController__/control.lua: 2348030623
  21.652 Checksum for script __YARM__/control.lua: 616803594
Factorio crashed. Generating symbolized stacktrace, please wait ...
c:\cygwin64\tmp\factorio-ri3osb\libraries\stackwalker\stackwalker.cpp (906): StackWalker::ShowCallstack
c:\cygwin64\tmp\factorio-ri3osb\src\util\logger.cpp (328): Logger::writeStacktrace
c:\cygwin64\tmp\factorio-ri3osb\src\util\logger.cpp (382): Logger::logStacktrace
c:\cygwin64\tmp\factorio-ri3osb\src\surface\chunk.cpp (564): Chunk::Chunk
c:\cygwin64\tmp\factorio-ri3osb\src\surface\surface.cpp (846): Surface::collideWithTile
c:\cygwin64\tmp\factorio-ri3osb\src\entity\entity.cpp (388): Entity::changePosition
c:\cygwin64\tmp\factorio-ri3osb\src\entity\unit.cpp (132): Unit::changePosition
c:\cygwin64\tmp\factorio-ri3osb\src\entity\unit.cpp (118): Unit::moveSmooth
c:\cygwin64\tmp\factorio-ri3osb\src\ai\gotobehavior.cpp (686): GotoBehavior::execute
c:\cygwin64\tmp\factorio-ri3osb\src\ai\followpathbehavior.cpp (160): FollowPathBehavior::execute
c:\cygwin64\tmp\factorio-ri3osb\src\ai\groupbehavior.cpp (151): GroupBehavior::execute
c:\cygwin64\tmp\factorio-ri3osb\src\ai\commandable.cpp (113): Commandable::runBehavior
c:\cygwin64\tmp\factorio-ri3osb\src\entity\unit.cpp (242): Unit::update
c:\cygwin64\tmp\factorio-ri3osb\src\surface\chunk.cpp (471): Chunk::update
c:\cygwin64\tmp\factorio-ri3osb\src\surface\surface.cpp (905): Surface::update
c:\cygwin64\tmp\factorio-ri3osb\src\map\map.cpp (1097): Map::update
c:\cygwin64\tmp\factorio-ri3osb\src\game.cpp (141): Game::update
c:\cygwin64\tmp\factorio-ri3osb\src\scenario\scenario.cpp (763): Scenario::update
c:\cygwin64\tmp\factorio-ri3osb\src\mainloop.cpp (337): MainLoop::gameUpdateStep
c:\cygwin64\tmp\factorio-ri3osb\src\mainloop.cpp (472): MainLoop::updateLoop
c:\program files (x86)\microsoft visual studio 14.0\vc\include\functional (214): std::_Func_impl<std::_Binder<std::_Unforced,void (__cdecl&)(ThreadBarrier * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,bool * __ptr64,bool,enum MainLoop::HeavyMode),ThreadBarrier * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,bool * __ptr64,bool & __ptr64,enum MainLoop::HeavyMode & __ptr64>,std::allocator<int>,void>::_Do_call
c:\cygwin64\tmp\factorio-ri3osb\src\util\thread.cpp (34): Thread::loop
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF7DD6C5103)
00007FF7DD6C5103 (factorio): (filename not available): boost::thread::start_thread_noexcept
d:\th\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp (115): thread_start<unsigned int (__cdecl*)(void * __ptr64)>
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF94D108102)
00007FF94D108102 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF950F4C5B4)
00007FF950F4C5B4 (ntdll): (filename not available): RtlUserThreadStart
  38.024 Error Chunk.cpp:564: Trying to make chunk at unreasonable position [262141, 262143]
Factorio crashed. Generating symbolized stacktrace, please wait ...
c:\cygwin64\tmp\factorio-ri3osb\libraries\stackwalker\stackwalker.cpp (906): StackWalker::ShowCallstack
c:\cygwin64\tmp\factorio-ri3osb\src\util\logger.cpp (328): Logger::writeStacktrace
c:\cygwin64\tmp\factorio-ri3osb\src\util\logger.cpp (382): Logger::logStacktrace
c:\cygwin64\tmp\factorio-ri3osb\src\util\crashhandler.cpp (84): CrashHandler::writeStackTrace
c:\cygwin64\tmp\factorio-ri3osb\src\util\crashhandler.cpp (186): CrashHandler::SignalHandler
d:\th\minkernel\crts\ucrt\src\appcrt\misc\signal.cpp (516): raise
d:\th\minkernel\crts\ucrt\src\appcrt\startup\abort.cpp (71): abort
c:\cygwin64\tmp\factorio-ri3osb\src\surface\chunk.cpp (564): Chunk::Chunk
c:\cygwin64\tmp\factorio-ri3osb\src\surface\surface.cpp (846): Surface::collideWithTile
c:\cygwin64\tmp\factorio-ri3osb\src\entity\entity.cpp (388): Entity::changePosition
c:\cygwin64\tmp\factorio-ri3osb\src\entity\unit.cpp (132): Unit::changePosition
c:\cygwin64\tmp\factorio-ri3osb\src\entity\unit.cpp (118): Unit::moveSmooth
c:\cygwin64\tmp\factorio-ri3osb\src\ai\gotobehavior.cpp (686): GotoBehavior::execute
c:\cygwin64\tmp\factorio-ri3osb\src\ai\followpathbehavior.cpp (160): FollowPathBehavior::execute
c:\cygwin64\tmp\factorio-ri3osb\src\ai\groupbehavior.cpp (151): GroupBehavior::execute
c:\cygwin64\tmp\factorio-ri3osb\src\ai\commandable.cpp (113): Commandable::runBehavior
c:\cygwin64\tmp\factorio-ri3osb\src\entity\unit.cpp (242): Unit::update
c:\cygwin64\tmp\factorio-ri3osb\src\surface\chunk.cpp (471): Chunk::update
c:\cygwin64\tmp\factorio-ri3osb\src\surface\surface.cpp (905): Surface::update
c:\cygwin64\tmp\factorio-ri3osb\src\map\map.cpp (1097): Map::update
c:\cygwin64\tmp\factorio-ri3osb\src\game.cpp (141): Game::update
c:\cygwin64\tmp\factorio-ri3osb\src\scenario\scenario.cpp (763): Scenario::update
c:\cygwin64\tmp\factorio-ri3osb\src\mainloop.cpp (337): MainLoop::gameUpdateStep
c:\cygwin64\tmp\factorio-ri3osb\src\mainloop.cpp (472): MainLoop::updateLoop
c:\program files (x86)\microsoft visual studio 14.0\vc\include\functional (214): std::_Func_impl<std::_Binder<std::_Unforced,void (__cdecl&)(ThreadBarrier * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,bool * __ptr64,bool,enum MainLoop::HeavyMode),ThreadBarrier * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,boost::chrono::time_point<boost::chrono::steady_clock,boost::chrono::duration<__int64,boost::ratio<1,1000000000> > > * __ptr64,bool * __ptr64,bool & __ptr64,enum MainLoop::HeavyMode & __ptr64>,std::allocator<int>,void>::_Do_call
c:\cygwin64\tmp\factorio-ri3osb\src\util\thread.cpp (34): Thread::loop
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF7DD6C5103)
00007FF7DD6C5103 (factorio): (filename not available): boost::thread::start_thread_noexcept
d:\th\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp (115): thread_start<unsigned int (__cdecl*)(void * __ptr64)>
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF94D108102)
00007FF94D108102 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF950F4C5B4)
00007FF950F4C5B4 (ntdll): (filename not available): RtlUserThreadStart
  38.764 Error CrashHandler.cpp:85: Map tick at moment of crash: 1095317
  38.764 Error Util.cpp:77: Unexpected error occurred. You can help us to solve the problem by posting the contents of the log file on the Factorio forums.
`

**Comment by kyranf** [comment] 2016-07-19 18:15
Hey Johan, I am doubtful that my mod caused the crash, see this line in the crash report:
"38.024 Error Chunk.cpp:564: Trying to make chunk at unreasonable position [262141, 262143]" 
My mod doesn't make chunks, I think there is something else going on.. Can you please submit this crash report and your save game file (autosave3) to the Bug Report section of the Factorio Forums https://forums.factorio.com/viewforum.php?f=7

**Comment by Johannnnnn** [comment] 2016-07-19 18:59
will do
my apologies :-)

2016-07-19 20:15 GMT+02:00 kyranf <notifications@github.com>:

**Comment by Johannnnnn** [comment] 2016-07-19 19:00
I must say - it stopped crashing after removing the Robot Army mod


2016-07-19 20:59 GMT+02:00 Johan Potums <johan.potums@gmail.com>:

**Comment by kyranf** [comment] 2016-07-19 19:02
It's possibly related to the bug which has been fixed  in 0.13.10 that is
caused by biter pathfinding/movement math that results in an invalid chunk.
Actually it does sound pretty spot on. Please wait for 0.13.10 release and
update to that to fix the issue. Get back to me if it doesn't :)

**Comment by kyranf** [comment] 2016-07-20 03:19
Oh by the way, i checked the log you posted again:
"21.652 Checksum for script __YARM__/control.lua: 616803594 Factorio crashed. " could be something weird going on in there too? I know you said it was with my mod, but that could be a coincidence

**Comment by kyranf** [comment] 2016-07-25 03:07
Can you comment on if this is fixed or not? I'd like to close this issue.

**Comment by Johannnnnn** [comment] 2016-07-25 08:52
I cannot. I overwrote the gamefile with another after filing the bugreport.
I am sorry i didn't know one would need it.

But i learned something. Next time will be better.

Op 25 jul. 2016 05:07 schreef "kyranf" <notifications@github.com>:

**Comment by kyranf** [comment] 2016-07-26 00:43
Closing until new evidence that the issue remains

**Closed by kyranf** 2016-07-26 00:43 UTC
